#!/bin/bash
# Open a pull request on GitHub for the current branch.
REPO=`git remote -v | grep "^origin.\+\(push\)" | perl -e 's/^.+github.com[:\/](.+)\.git.+$/$1/' -pi`
BRANCH=`git current-branch`

git push -u origin $BRANCH
open "https://github.com/$REPO/compare/$BRANCH?expand=1"
