# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

WORKING_DIR = 'tmp/scratch'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before do
    FileUtils.rm_rf(WORKING_DIR)
    init_repo
  end
end

def init_repo
  FileUtils.mkdir_p(WORKING_DIR)
  Dir.chdir(WORKING_DIR)
  `git init`
end

def execute(command)
  # ensure the scripts from this repository are used
  script_path = File.join(File.dirname(__FILE__), '..')
  `PATH=#{script_path}:$PATH #{command}`
end
